Repository Team-Cherry-Pick/cherrypick-spring-boot, pull requests merged in 2025-04, with the labels that each got.

#1 RP-35 프로젝트 초기 세팅
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/cherrypick/backend/CherrypickBackendApplication.java
  src/main/java/com/cherrypick/backend/domain/category/entity/Category.java
  src/main/java/com/cherrypick/backend/domain/comment/entity/Comment.java
  src/main/java/com/cherrypick/backend/domain/comment/entity/CommentLike.java
  src/main/java/com/cherrypick/backend/domain/comment/entity/CommentLikeId.java
  src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java
  src/main/java/com/cherrypick/backend/domain/deal/enums/PriceType.java
  src/main/java/com/cherrypick/backend/domain/deal/enums/ShippingType.java
  src/main/java/com/cherrypick/backend/domain/deal/vo/Price.java
  src/main/java/com/cherrypick/backend/domain/deal/vo/Shipping.java
  src/main/java/com/cherrypick/backend/domain/discount/entity/Discount.java
  src/main/java/com/cherrypick/backend/domain/image/entity/Image.java
  src/main/java/com/cherrypick/backend/domain/store/entity/Store.java
  src/main/java/com/cherrypick/backend/domain/user/entity/User.java
  src/main/java/com/cherrypick/backend/domain/vote/entity/Vote.java
  src/main/java/com/cherrypick/backend/domain/vote/enums/voteType.java
  src/main/java/com/cherrypick/backend/global/config/CorsConfig.java
  src/main/java/com/cherrypick/backend/global/exception/BaseErrorCode.java
  src/main/java/com/cherrypick/backend/global/exception/BaseException.java
  src/main/java/com/cherrypick/backend/global/exception/dto/response/ErrorResponseDTO.java
  src/main/java/com/cherrypick/backend/global/exception/enums/GlobalErrorCode.java
  src/main/java/com/cherrypick/backend/global/exception/enums/UserErrorCode.java
  src/main/java/com/cherrypick/backend/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/cherrypick/backend/global/util/SlackNotifier.java
  src/main/resources/application.yml
  src/test/java/com/cherrypick/backend/CherrypickBackendApplicationTests.java
Labels: feat

#6 RP-34 스웨거 적용
  build.gradle
  src/main/java/com/cherrypick/backend/domain/user/controller/UserController.java
  src/main/java/com/cherrypick/backend/global/config/SecurityConfig.java
  src/main/java/com/cherrypick/backend/global/config/SwaggerConfig.java
  src/main/java/com/cherrypick/backend/global/config/oauth/FilterChainExceptionHandler.java
  src/main/java/com/cherrypick/backend/global/config/oauth/JWTFilter.java
  src/main/java/com/cherrypick/backend/global/config/oauth/OAuth2Service.java
  src/main/java/com/cherrypick/backend/global/exception/enums/UserErrorCode.java
  src/main/java/com/cherrypick/backend/global/util/JWTUtil.java
Labels: build, feat

#8 RP-18 핫딜 게시글 투표 기능 구현
  src/main/java/com/cherrypick/backend/domain/deal/dto/request/DealCreateRequestDTO.java
  src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
  src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java
  src/main/java/com/cherrypick/backend/domain/vote/dto/request/VoteRequestDTO.java
  src/main/java/com/cherrypick/backend/domain/vote/dto/response/VoteResponseDTO.java
  src/main/java/com/cherrypick/backend/domain/vote/entity/Vote.java
  src/main/java/com/cherrypick/backend/domain/vote/enums/DislikeReason.java
  src/main/java/com/cherrypick/backend/domain/vote/enums/VoteType.java
  src/main/java/com/cherrypick/backend/domain/vote/repository/VoteRepository.java
  src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java
  src/main/java/com/cherrypick/backend/global/exception/enums/VoteErrorCode.java
Labels: feat

#9 RP-28 리프레시 토큰 발급
  build.gradle
  src/main/java/com/cherrypick/backend/domain/oauth/controller/AuthController.java
  src/main/java/com/cherrypick/backend/domain/oauth/dto/AuthResponseDTOs.java
  src/main/java/com/cherrypick/backend/domain/oauth/dto/OAuth2LoginSuccessResponseDTO.java
  src/main/java/com/cherrypick/backend/domain/oauth/dto/OAuth2UserDTO.java
  src/main/java/com/cherrypick/backend/domain/oauth/service/AuthService.java
  src/main/java/com/cherrypick/backend/domain/user/dto/UserDetailDTO.java
  src/main/java/com/cherrypick/backend/global/config/RedisConfig.java
  src/main/java/com/cherrypick/backend/global/config/SecurityConfig.java
  src/main/java/com/cherrypick/backend/global/config/oauth/OAuth2LoginSuccessResponseDTO.java
  src/main/java/com/cherrypick/backend/global/config/security/CustomAuthorizationRequestResolver.java
  src/main/java/com/cherrypick/backend/global/config/security/FilterChainExceptionHandler.java
  src/main/java/com/cherrypick/backend/global/config/security/JWTFilter.java
  src/main/java/com/cherrypick/backend/global/config/security/OAuth2SuccessHandler.java
  src/main/java/com/cherrypick/backend/global/exception/enums/UserErrorCode.java
  src/main/java/com/cherrypick/backend/global/util/AuthUtil.java
  src/main/java/com/cherrypick/backend/global/util/JWTUtil.java
  src/main/resources/application.yml
Labels: refactor, feat

#17 [RP-9] CI/CD 구축
  .github/workflows/deploy.yml
  dockerfile
Labels: build

#19 RP-9 CI/CD 테스트 배포
  src/main/java/com/cherrypick/backend/domain/deal/controller/DealController.java
  src/main/java/com/cherrypick/backend/domain/image/controller/ImageController.java
  src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java
Labels: build

#24 RP-10 핫딜 전체 조회(검색) 페이징 처리 및 N+1 문제 해결
  src/main/java/com/cherrypick/backend/domain/comment/repository/CommentRepository.java
  src/main/java/com/cherrypick/backend/domain/deal/controller/DealController.java
  src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealSearchPageResponseDTO.java
  src/main/java/com/cherrypick/backend/domain/deal/repository/DealRepository.java
  src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
  src/main/java/com/cherrypick/backend/domain/image/repository/ImageRepository.java
  src/main/java/com/cherrypick/backend/domain/vote/controller/VoteController.java
  src/main/java/com/cherrypick/backend/domain/vote/enums/DislikeReason.java
  src/main/java/com/cherrypick/backend/domain/vote/repository/VoteRepository.java
Labels: feat
