Repository Team-Cherry-Pick/cherrypick-spring-boot, pull requests merged in 2025-09, with the labels that each got.

#75 RP-117 실적조회 API 구현 및 Q/A 해결
  build.gradle
  src/main/java/com/cherrypick/backend/domain/comment/service/CommentService.java
  src/main/java/com/cherrypick/backend/domain/deal/repository/DealRepository.java
  src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
  src/main/java/com/cherrypick/backend/domain/linkprice/controller/LinkPriceController.java
  src/main/java/com/cherrypick/backend/domain/linkprice/controller/LinkPriceSchedulers.java
  src/main/java/com/cherrypick/backend/domain/linkprice/dto/request/LinkPriceRequest.java
  src/main/java/com/cherrypick/backend/domain/linkprice/dto/response/LinkPriceResponse.java
  src/main/java/com/cherrypick/backend/domain/linkprice/entity/LinkPriceTransaction.java
  src/main/java/com/cherrypick/backend/domain/linkprice/repository/LinkPriceTransactionRepository.java
  src/main/java/com/cherrypick/backend/domain/linkprice/service/LinkPriceService.java
  src/main/java/com/cherrypick/backend/domain/linkprice/service/LinkPriceTransactionService.java
  src/main/java/com/cherrypick/backend/domain/store/vo/Store.java
  src/main/java/com/cherrypick/backend/global/config/SecurityConfig.java
  src/main/java/com/cherrypick/backend/global/config/WebClientConfig.java
  src/main/java/com/cherrypick/backend/global/exception/enums/LinkPriceErrorCode.java
  src/main/resources/application.yml
Labels: error, feat

#76 RP-175 핫딜 온도 개편
  src/main/java/com/cherrypick/backend/domain/deal/adapter/out/RedisDuplicationPreventionAdapter.java
  src/main/java/com/cherrypick/backend/domain/deal/controller/DealController.java
  src/main/java/com/cherrypick/backend/domain/deal/entity/Deal.java
  src/main/java/com/cherrypick/backend/domain/deal/repository/DealRepository.java
  src/main/java/com/cherrypick/backend/domain/deal/service/DealLogService.java
  src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
  src/main/java/com/cherrypick/backend/domain/deal/vo/Filter.java
  src/main/java/com/cherrypick/backend/domain/deal/vo/Price.java
  src/main/java/com/cherrypick/backend/domain/deal/vo/PriceFilter.java
  src/main/java/com/cherrypick/backend/domain/deal/vo/Shipping.java
  src/main/java/com/cherrypick/backend/domain/store/vo/Store.java
  src/main/java/com/cherrypick/backend/domain/vote/service/VoteService.java
  src/main/java/com/cherrypick/backend/global/util/LogService.java
Labels: feat

#77 RP-176 뱃지 시스템 구현 (베타테스터)
  src/main/java/com/cherrypick/backend/domain/auth/application/AuthService.java
  src/main/java/com/cherrypick/backend/domain/comment/dto/response/BestCommentResponseDTO.java
  src/main/java/com/cherrypick/backend/domain/comment/dto/response/CommentListResponseDTO.java
  src/main/java/com/cherrypick/backend/domain/comment/service/CommentService.java
  src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealDetailResponseDTO.java
  src/main/java/com/cherrypick/backend/domain/deal/dto/response/DealSearchResponseDTO.java
  src/main/java/com/cherrypick/backend/domain/deal/service/DealService.java
  src/main/java/com/cherrypick/backend/domain/deal/service/RecommenderService.java
  src/main/java/com/cherrypick/backend/domain/user/controller/UserController.java
  src/main/java/com/cherrypick/backend/domain/user/dto/UserRequestDTOs.java
  src/main/java/com/cherrypick/backend/domain/user/dto/UserResponseDTOs.java
  src/main/java/com/cherrypick/backend/domain/user/dto/request/UserRequestDTOs.java
  src/main/java/com/cherrypick/backend/domain/user/dto/request/UserUpdateRequestDTO.java
  src/main/java/com/cherrypick/backend/domain/user/dto/response/UserDetailResponseDTO.java
  src/main/java/com/cherrypick/backend/domain/user/dto/response/UserResponseDTOs.java
  src/main/java/com/cherrypick/backend/domain/user/entity/Badge.java
  src/main/java/com/cherrypick/backend/domain/user/entity/User.java
  src/main/java/com/cherrypick/backend/domain/user/entity/UserBadge.java
  src/main/java/com/cherrypick/backend/domain/user/repository/BadgeRepository.java
  src/main/java/com/cherrypick/backend/domain/user/repository/UserBadgeRepository.java
  src/main/java/com/cherrypick/backend/domain/user/service/BadgeService.java
  src/main/java/com/cherrypick/backend/domain/user/service/UserService.java
  src/main/java/com/cherrypick/backend/domain/user/vo/UserVO.java
  src/main/java/com/cherrypick/backend/global/config/SecurityConfig.java
  src/main/java/com/cherrypick/backend/global/config/SwaggerConfig.java
  src/main/java/com/cherrypick/backend/global/exception/enums/BadgeErrorCode.java
  src/test/java/com/cherrypick/backend/domain/user/service/UserServiceTest.java
Labels: refactor, feat
